seed: 42

model:
  name: vit_tiny_patch16_224
  num_classes: 0
  pretrained: false
  embed_dim: 192
  # mimetic init
  mimetic_init: true
  mimetic_alpha: 0.4
  mimetic_beta: 0.4
  mimetic_dist: uniform

grid: { H: 14, W: 14 }

vocab:
  K: 130
  PAD_ID: 0
  MASK_ID: 1

dyck:
  k_open: 64
  k_close: 64
  open_prob: 0.6
  min_pairs: 1

dataset:
  n_samples: 20000
  num_workers: 4
  pin_memory: true
  use_shuffled: false
  batch_size: 256

training:
  steps: 15000
  mask_ratio: 0.50
  device: cuda

optimizer:
  name: AdamW
  lr: 0.002
  weight_decay: 0.05
  betas: [0.9, 0.999]

scheduler:
  enabled: true
  type: cosine
  warmup_steps: 1000
  min_lr: 0.000001

grad_clip: { enabled: false }

checkpoint:
  dir: spt_models/dyck-mlm/v7_1.2/close-only/
  save_steps: [15000]

wandb:
  enabled: true
  project: dyck-mlm
  name: v7_1.2
  tags: ["dyck","mlm","vit-tiny"]

logging:
  print_freq: 100
  log_examples: false
